Add a RelationList form field type handler
netgen/NetgenEzFormsBundle pull request #40
Opened 2017-11-20 10:59 UTC by tbuljevic

This is a very shallow implementation of the ezobjectrelationlist form field type handler which only shows a dropdown. It is prepped to be expanded with other selection types, though, and a switch statement controls the possible implementations of the other selection types in question.

2017-11-20 12:53 UTC, MarioBlazek commented
Looks good @tbuljevic, it would be nice to have some unit tests for `RelationList` class. For everything else 👍 .

2017-11-20 12:54 UTC, MarioBlazek requested changes
`RelationList` unit test missing.

2017-11-20 13:49 UTC, emodric commented
You should run `php-cs-fixer fix` to correct coding standards, but otherwise :+1:

2018-05-21 20:17 UTC, amirkoklan commented
can't we have this one merged ? are we allowed to contribute/ go on this branch/work?

2018-05-21 20:45 UTC, MarioBlazek commented
@amirkoklan we can merge this one, you can add your changes in followup PR. WDYT ?

2018-05-21 20:48 UTC, amirkoklan commented
I would call it "the best"! 
because fork from a fork is not really clean and good :)

2018-05-21 20:56 UTC, merged

2018-05-21 20:56 UTC, MarioBlazek commented
@amirkoklan it is your turn now :)

2018-05-22 12:57 UTC, wzrigui commented
This have an error, it would be fixed if you add
`use eZ\Publish\Core\FieldType\RelationList\Value as RelationListValue;`

2018-05-22 13:09 UTC, MarioBlazek commented
@wzrigui thanks.